---
sidebar: sidebar 
permalink: scpivs44_restore_from_backups_overview.html 
keywords:  
summary: È possibile ripristinare macchine virtuali, VMDK, file e cartelle da backup primari o secondari. 
---
= Panoramica
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile ripristinare macchine virtuali, VMDK, file e cartelle da backup primari o secondari.

* Destinazioni di ripristino delle macchine virtuali
+
Nel plug-in SnapCenter per VMware vSphere 4.4 e versioni precedenti, è possibile ripristinare le macchine virtuali solo sull'host e sul datastore originali.

+
A partire dal plug-in SnapCenter per VMware vSphere 4.5, è possibile ripristinare le macchine virtuali sull'host originale o su un host alternativo nello stesso server vCenter o su un host ESXi alternativo gestito dallo stesso vCenter o da qualsiasi vCenter in modalità collegata.

* Destinazioni di ripristino VMDK
+
È possibile ripristinare i VMDK sull'originale o su un datastore alternativo.



È inoltre possibile ripristinare singoli file e cartelle in una sessione di ripristino dei file guest, che allega una copia di backup di un disco virtuale e ripristina i file o le cartelle selezionati.

Non è possibile ripristinare quanto segue:

* Datastore
+
Non è possibile utilizzare il plug-in SnapCenter per VMware vSphere per ripristinare un datastore, solo le singole macchine virtuali presenti nel datastore.

* Backup delle macchine virtuali rimosse
+
Non è possibile ripristinare i backup delle VM di storage che sono state rimosse. Ad esempio, se si aggiunge una VM di storage utilizzando la LIF di gestione e si crea un backup, quindi si rimuove la VM di storage e si aggiunge un cluster contenente la stessa VM di storage, l'operazione di ripristino del backup non avrà esito positivo.


